<?php
global $base_url; // Will point to http://www.example.com
/**
 * Implements hook_menu().
 */
function osdag_response_form_menu()
{
	$items = array();
	// Form page.
	/****************** Seated Angle Connection DDQ (Design and Detailing Queries)******************/
	$items['ddcl-osdag-response/form'] = array(
		'title' => t('Seated Angle Connection DDQ (Design and Detailing Queries)'),
		'page callback' => 'ddcl_osdag_response_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_osdag_response.inc'
	);
	$items['ddcl-osdag-response/form/step1'] = array(
		'title' => t('Seated Angle Connection DDQ (Design and Detailing Queries)'),
		'page callback' => 'ddcl_osdag_response_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_osdag_response.inc'
	);
	$items['ddcl-osdag-response/form/step2'] = array(
		'title' => t('Seated Angle Connection DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_osdag_response_step2_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_osdag_response.inc'
	);
	$items['ddcl-osdag-response/form/step3'] = array(
		'title' => t('Seated Angle Connection DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_osdag_response_step3_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_osdag_response.inc'
	);
	$items['ddcl-osdag-response/form/step4'] = array(
		'title' => t('Seated Angle Connection DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_osdag_response_step4_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_osdag_response.inc'
	);
	$items['ddcl-osdag-response/form/step5'] = array(
		'title' => t('Seated Angle Connection DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_osdag_response_step5_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_osdag_response.inc'
	);
	$items['ddcl-osdag-response/form/step6'] = array(
		'title' => t('Seated Angle Connection DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_osdag_response_step6_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_osdag_response.inc'
	);
	$items['ddcl-osdag-response/form/step7'] = array(
		'title' => t('Seated Angle Connection DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_osdag_response_step7_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_osdag_response.inc'
	);
	$items['ddcl-osdag-response/form/step8'] = array(
		'title' => t('Seated Angle Connection DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_osdag_response_step8_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_osdag_response.inc'
	);
	// Delete the comment
	$items['ddcl-osdag-response/delete'] = array(
		'title' => t('Seated Angle Connection DDQ (Design and Detailing Queries) successful!'),
		'page callback' => 'ddcl_osdag_response_delete_comment',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_osdag_response.inc'
	);
	// Success page.
	$items['ddcl-osdag-response/success'] = array(
		'title' => t('Seated Angle Connection DDQ (Design and Detailing Queries) successful!'),
		'page callback' => 'ddcl_osdag_response_success',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_osdag_response.inc'
	);
	// Result page
	$items['ddcl-osdag-response/form/result'] = array(
		'title' => t('Seated Angle Connection DDQ (Design and Detailing Queries)'),
		'page callback' => 'ddcl_osdag_response_result_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_osdag_response.inc'
	);
	$items['ddcl-osdag-response/form/result/download'] = array(
		'title' => t('Seated Angle Connection DDQ (Design and Detailing Queries)'),
		'page callback' => 'ddcl_result_generate_csv',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_osdag_response.inc'
	);
	/***********************************************************/
	/****************** DDCL SEATED ANGlE FORM ******************/
	$items['ddcl-seated-angle/form'] = array(
		'title' => t('Seated Angle Connection DDCL (Design and Detailing Check-
List)'),
		'page callback' => 'ddcl_seated_angle_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_seated_angle.inc'
	);
	$items['ddcl-seated-angle/form/step1'] = array(
		'title' => t('Seated Angle Connection DDCL (Design and Detailing Check-
List)'),
		'page callback' => 'ddcl_seated_angle_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_seated_angle.inc'
	);
	$items['ddcl-seated-angle/form/step2'] = array(
		'title' => t('Seated Angle Connection DDCL (Design and Detailing Check-
List)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_seated_angle_step2_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_seated_angle.inc'
	);
	$items['ddcl-seated-angle/form/step3'] = array(
		'title' => t('Seated Angle Connection DDCL (Design and Detailing Check-
List)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_seated_angle_step3_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_seated_angle.inc'
	);
	$items['ddcl-seated-angle/form/step4'] = array(
		'title' => t('Seated Angle Connection DDCL (Design and Detailing Check-
List)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_seated_angle_step4_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_seated_angle.inc'
	);
	$items['ddcl-seated-angle/form/step5'] = array(
		'title' => t('Seated Angle Connection DDCL (Design and Detailing Check-
List)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_seated_angle_step5_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_seated_angle.inc'
	);
	$items['ddcl-seated-angle/form/step6'] = array(
		'title' => t('Seated Angle Connection DDCL (Design and Detailing Check-
List)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_seated_angle_step6_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_seated_angle.inc'
	);
	$items['ddcl-seated-angle/form/step7'] = array(
		'title' => t('Seated Angle Connection DDCL (Design and Detailing Check-
List)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_seated_angle_step7_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_seated_angle.inc'
	);
	$items['ddcl-seated-angle/form/step8'] = array(
		'title' => t('Seated Angle Connection DDCL (Design and Detailing Check-
List)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_seated_angle_step8_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_seated_angle.inc'
	);
	$items['ddcl-seated-angle/form/step9'] = array(
		'title' => t('Seated Angle Connection DDCL (Design and Detailing Check-
List)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_seated_angle_step9_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_seated_angle.inc'
	);
	$items['ddcl-seated-angle/form/step10'] = array(
		'title' => t('Seated Angle Connection DDCL (Design and Detailing Check-
List)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_seated_angle_step10_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_seated_angle.inc'
	);
	$items['ddcl-seated-angle/form/step11'] = array(
		'title' => t('Seated Angle Connection DDCL (Design and Detailing Check-
List)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_seated_angle_step11_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_seated_angle.inc'
	);
	$items['ddcl-seated-angle/form/step12'] = array(
		'title' => t('Seated Angle Connection DDCL (Design and Detailing Check-
List)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_seated_angle_step12_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_seated_angle.inc'
	);
	$items['ddcl-seated-angle/form/step13'] = array(
		'title' => t('Seated Angle Connection DDCL (Design and Detailing Check-
List)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_seated_angle_step13_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_seated_angle.inc'
	);
	$items['ddcl-seated-angle/form/step14'] = array(
		'title' => t('Seated Angle Connection DDCL (Design and Detailing Check-
List)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_seated_angle_step14_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_seated_angle.inc'
	);
	// Delete the comment
	$items['ddcl-seated-angle/delete'] = array(
		'title' => t('Seated Angle Connection DDCL (Design and Detailing Check-
List)'),
		'page callback' => 'ddcl_seated_angle_delete_comment',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_seated_angle.inc'
	);
	// Success page.
	$items['ddcl-seated-angle/success'] = array(
		'title' => t('Seated Angle Connection DDCL (Design and Detailing Check-
List)'),
		'page callback' => 'ddcl_seated_angle_success',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_seated_angle.inc'
	);
	// Result page
	$items['ddcl-seated-angle/form/result'] = array(
		'title' => t('Seated Angle Connection DDCL (Design and Detailing Check-
List)'),
		'page callback' => 'ddcl_seated_angle_response_result_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_seated_angle.inc'
	);
	$items['ddcl-seated-angle/form/result/download'] = array(
		'title' => t('Seated Angle Connection DDCL (Design and Detailing Check-
List)'),
		'page callback' => 'ddcl_seated_angle_result_generate_csv',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_seated_angle.inc'
	);
	/*******************************************************************/
	/************* DDCL FIN PLATE **************************************/
	$items['ddcl-fin-plate/form'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'ddcl_fin_plate_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
	$items['ddcl-fin-plate/form/step1'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'ddcl_fin_plate_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
	$items['ddcl-fin-plate/form/step2'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_fin_plate_step2_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
	$items['ddcl-fin-plate/form/step3'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_fin_plate_step3_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
	$items['ddcl-fin-plate/form/step4'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_fin_plate_step4_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
	$items['ddcl-fin-plate/form/step5'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_fin_plate_step5_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
	$items['ddcl-fin-plate/form/step6'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_fin_plate_step6_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
	$items['ddcl-fin-plate/form/step7'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_fin_plate_step7_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
	$items['ddcl-fin-plate/form/step8'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_fin_plate_step8_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
	$items['ddcl-fin-plate/form/step9'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_fin_plate_step9_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
	$items['ddcl-fin-plate/form/step10'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_fin_plate_step10_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
	$items['ddcl-fin-plate/form/step11'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_fin_plate_step11_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
	$items['ddcl-fin-plate/form/step12'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_fin_plate_step12_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
	$items['ddcl-fin-plate/form/step13'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_fin_plate_step13_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
	$items['ddcl-fin-plate/form/step14'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_fin_plate_step14_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
	$items['ddcl-fin-plate/form/step15'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_fin_plate_step15_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
	$items['ddcl-fin-plate/form/step16'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_fin_plate_step16_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
	$items['ddcl-fin-plate/form/step17'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_fin_plate_step17_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
	// Delete the comment
	$items['ddcl-fin-plate/delete'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'ddcl_fin_plate_delete_comment',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
	// Success page.
	$items['ddcl-fin-plate/success'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'ddcl_fin_plate_success',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
	// Result page
	$items['ddcl-fin-plate/form/result'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'ddcl_fin_plate_result_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
	$items['ddcl-fin-plate/form/result/download'] = array(
		'title' => t('DDCL Fin Plate'),
		'page callback' => 'ddcl_fin_plate_result_generate_csv',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_fin_plate.inc'
	);
/*******************************************************************/
	/************* DDCL END PLATE **************************************/
	$items['ddcl-end-plate/form'] = array(
		'title' => t('DDCL End Plate'),
		'page callback' => 'ddcl_end_plate_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_end_plate.inc'
	);
	$items['ddcl-end-plate/form/step1'] = array(
		'title' => t('DDCL End Plate'),
		'page callback' => 'ddcl_end_plate_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_end_plate.inc'
	);
	$items['ddcl-end-plate/form/step2'] = array(
		'title' => t('DDCL End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_end_plate_step2_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_end_plate.inc'
	);
	$items['ddcl-end-plate/form/step3'] = array(
		'title' => t('DDCL End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_end_plate_step3_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_end_plate.inc'
	);
	$items['ddcl-end-plate/form/step4'] = array(
		'title' => t('DDCL End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_end_plate_step4_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_end_plate.inc'
	);
	$items['ddcl-end-plate/form/step5'] = array(
		'title' => t('DDCL End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_end_plate_step5_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_end_plate.inc'
	);
	$items['ddcl-end-plate/form/step6'] = array(
		'title' => t('DDCL End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_end_plate_step6_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_end_plate.inc'
	);
	$items['ddcl-end-plate/form/step7'] = array(
		'title' => t('DDCL End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_end_plate_step7_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_end_plate.inc'
	);
	$items['ddcl-end-plate/form/step8'] = array(
		'title' => t('DDCL End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_end_plate_step8_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_end_plate.inc'
	);
	$items['ddcl-end-plate/form/step9'] = array(
		'title' => t('DDCL End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_end_plate_step9_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_end_plate.inc'
	);
	$items['ddcl-end-plate/form/step10'] = array(
		'title' => t('DDCL End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_end_plate_step10_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_end_plate.inc'
	);
	$items['ddcl-end-plate/form/step11'] = array(
		'title' => t('DDCL End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_end_plate_step11_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_end_plate.inc'
	);
	$items['ddcl-end-plate/form/step12'] = array(
		'title' => t('DDCL End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_end_plate_step12_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_end_plate.inc'
	);
	$items['ddcl-end-plate/form/step13'] = array(
		'title' => t('DDCL End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_end_plate_step13_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_end_plate.inc'
	);
	$items['ddcl-end-plate/form/step14'] = array(
		'title' => t('DDCL End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_end_plate_step14_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_end_plate.inc'
	);
	$items['ddcl-end-plate/form/step15'] = array(
		'title' => t('DDCL End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_end_plate_step15_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_end_plate.inc'
	);
	
	// Delete the comment
	$items['ddcl-end-plate/delete'] = array(
		'title' => t('DDCL End Plate'),
		'page callback' => 'ddcl_end_plate_delete_comment',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_end_plate.inc'
	);
	// Success page.
	$items['ddcl-end-plate/success'] = array(
		'title' => t('DDCL End Plate'),
		'page callback' => 'ddcl_end_plate_success',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_end_plate.inc'
	);
	// Result page
	$items['ddcl-end-plate/form/result'] = array(
		'title' => t('DDCL End Plate'),
		'page callback' => 'ddcl_end_plate_result_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_end_plate.inc'
	);
	$items['ddcl-end-plate/form/result/download'] = array(
		'title' => t('DDCL End Plate'),
		'page callback' => 'ddcl_end_plate_result_generate_csv',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_end_plate.inc'
	);
	/*******************************************************************/
	/************* DDCL BB Splice Extended End Plate **************************************/
	$items['ddcl-bb-splice-extended-end-plate/form'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'ddcl_bb_splice_end_plate_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step1'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'ddcl_bb_splice_end_plate_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step2'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step2_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step3'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step3_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step4'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step4_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step5'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step5_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step6'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step6_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step7'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step7_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step8'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step8_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step9'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step9_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step10'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step10_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step11'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step11_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step12'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step12_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step13'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step13_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step14'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step14_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step15'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step15_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step16'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step16_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step17'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step17_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step18'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step18_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step19'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step19_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step20'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step20_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step21'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step21_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step22'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step22_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step23'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step23_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step24'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step24_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step25'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step25_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/step26'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_end_plate_step26_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	
	// Delete the comment
	$items['ddcl-bb-splice-extended-end-plate/delete'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'ddcl_bb_splice_end_plate_delete_comment',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	// Success page.
	$items['ddcl-bb-splice-extended-end-plate/success'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'ddcl_bb_splice_end_plate_success',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	// Result page
	$items['ddcl-bb-splice-extended-end-plate/form/result'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'ddcl_bb_splice_end_plate_result_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	$items['ddcl-bb-splice-extended-end-plate/form/result/download'] = array(
		'title' => t('DDCL BB Splice Extended End Plate'),
		'page callback' => 'ddcl_bb_splice_end_plate_result_generate_csv',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_end_plate.inc'
	);
	/*******************************************************************/
	/************* DDCL Cleat Angle **************************************/
	$items['ddcl-cleat-angle/form'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'ddcl_cleat_angle_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	$items['ddcl-cleat-angle/form/step1'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'ddcl_cleat_angle_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	$items['ddcl-cleat-angle/form/step2'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_cleat_angle_step2_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	$items['ddcl-cleat-angle/form/step3'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_cleat_angle_step3_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	$items['ddcl-cleat-angle/form/step4'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_cleat_angle_step4_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	$items['ddcl-cleat-angle/form/step5'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_cleat_angle_step5_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	$items['ddcl-cleat-angle/form/step6'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_cleat_angle_step6_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	$items['ddcl-cleat-angle/form/step7'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_cleat_angle_step7_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	$items['ddcl-cleat-angle/form/step8'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_cleat_angle_step8_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	$items['ddcl-cleat-angle/form/step9'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_cleat_angle_step9_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	$items['ddcl-cleat-angle/form/step10'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_cleat_angle_step10_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	$items['ddcl-cleat-angle/form/step11'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_cleat_angle_step11_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	$items['ddcl-cleat-angle/form/step12'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_cleat_angle_step12_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	$items['ddcl-cleat-angle/form/step13'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_cleat_angle_step13_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	$items['ddcl-cleat-angle/form/step14'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_cleat_angle_step14_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	$items['ddcl-cleat-angle/form/step15'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_cleat_angle_step15_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	$items['ddcl-cleat-angle/form/step16'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_cleat_angle_step16_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	$items['ddcl-cleat-angle/form/step17'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_cleat_angle_step17_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	// Delete the comment
	$items['ddcl-cleat-angle/delete'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'ddcl_cleat_angle_delete_comment',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	// Success page.
	$items['ddcl-cleat-angle/success'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'ddcl_cleat_angle_success',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	// Result page
	$items['ddcl-cleat-angle/form/result'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'ddcl_cleat_angle_result_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	$items['ddcl-cleat-angle/form/result/download'] = array(
		'title' => t('DDCL Cleat Angle'),
		'page callback' => 'ddcl_cleat_angle_result_generate_csv',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_cleat_angle.inc'
	);
	/*******************************************************************/
	/****************** DDQ Fin Plate ******************/
	$items['ddq-fin-plate/form'] = array(
		'title' => t('Fin plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'ddq_fin_plate_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_fin_plate.inc'
	);
	$items['ddq-fin-plate/form/step1'] = array(
		'title' => t('Fin plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'ddq_fin_plate_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_fin_plate.inc'
	);
	$items['ddq-fin-plate/form/step2'] = array(
		'title' => t('Fin plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_fin_plate_step2_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_fin_plate.inc'
	);
	$items['ddq-fin-plate/form/step3'] = array(
		'title' => t('Fin plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_fin_plate_step3_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_fin_plate.inc'
	);
	$items['ddq-fin-plate/form/step4'] = array(
		'title' => t('Fin plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_fin_plate_step4_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_fin_plate.inc'
	);
	$items['ddq-fin-plate/form/step5'] = array(
		'title' => t('Fin plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_fin_plate_step5_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_fin_plate.inc'
	);
	$items['ddq-fin-plate/form/step6'] = array(
		'title' => t('Fin plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_fin_plate_step6_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_fin_plate.inc'
	);
	// Delete the comment
	$items['ddq-fin-plate/delete'] = array(
		'title' => t('Fin plate DDQ (Design and Detailing Queries) successful!'),
		'page callback' => 'ddq_fin_plate_delete_comment',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_fin_plate.inc'
	);
	// Success page.
	$items['ddq-fin-plate/success'] = array(
		'title' => t('Fin plate DDQ (Design and Detailing Queries) successful!'),
		'page callback' => 'ddq_fin_plate_success',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_fin_plate.inc'
	);
	// Result page
	$items['ddq-fin-plate/form/result'] = array(
		'title' => t('Fin plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'ddq_fin_plate_result_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_fin_plate.inc'
	);
	$items['ddq-fin-plate/form/result/download'] = array(
		'title' => t('Fin plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'ddq_fin_plate_result_generate_csv',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_fin_plate.inc'
	);

	/*******************************************************************/
	/****************** DDQ End Plate ******************/
	$items['ddq-end-plate/form'] = array(
		'title' => t('End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'ddq_end_plate_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_end_plate.inc'
	);
	$items['ddq-end-plate/form/step1'] = array(
		'title' => t('End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'ddq_end_plate_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_end_plate.inc'
	);
	$items['ddq-end-plate/form/step2'] = array(
		'title' => t('End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_end_plate_step2_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_end_plate.inc'
	);
	$items['ddq-end-plate/form/step3'] = array(
		'title' => t('End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_end_plate_step3_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_end_plate.inc'
	);
	$items['ddq-end-plate/form/step4'] = array(
		'title' => t('End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_end_plate_step4_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_end_plate.inc'
	);
	$items['ddq-end-plate/form/step5'] = array(
		'title' => t('End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_end_plate_step5_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_end_plate.inc'
	);
	$items['ddq-end-plate/form/step6'] = array(
		'title' => t('End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_end_plate_step6_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_end_plate.inc'
	);
	// Delete the comment
	$items['ddq-end-plate/delete'] = array(
		'title' => t('End plate DDQ (Design and Detailing Queries) successful!'),
		'page callback' => 'ddq_end_plate_delete_comment',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_end_plate.inc'
	);
	// Success page.
	$items['ddq-end-plate/success'] = array(
		'title' => t('End plate DDQ (Design and Detailing Queries) successful!'),
		'page callback' => 'ddq_end_plate_success',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_end_plate.inc'
	);
	// Result page
	$items['ddq-end-plate/form/result'] = array(
		'title' => t('End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'ddq_end_plate_result_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_end_plate.inc'
	);
	$items['ddq-end-plate/form/result/download'] = array(
		'title' => t('End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'ddq_end_plate_result_generate_csv',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_end_plate.inc'
	);
	/*******************************************************************/
	/****************** DDQ BB Splice End Plate ******************/
	$items['ddq-bb-splice-extended-end-plate/form'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'ddq_bb_splice_end_plate_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
	$items['ddq-bb-splice-extended-end-plate/form/step1'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'ddq_bb_splice_end_plate_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
	$items['ddq-bb-splice-extended-end-plate/form/step2'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_bb_splice_end_plate_step2_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
	$items['ddq-bb-splice-extended-end-plate/form/step3'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_bb_splice_end_plate_step3_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
	$items['ddq-bb-splice-extended-end-plate/form/step4'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_bb_splice_end_plate_step4_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
	$items['ddq-bb-splice-extended-end-plate/form/step5'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_bb_splice_end_plate_step5_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
	$items['ddq-bb-splice-extended-end-plate/form/step6'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_bb_splice_end_plate_step6_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
		$items['ddq-bb-splice-extended-end-plate/form/step7'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_bb_splice_end_plate_step7_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
	$items['ddq-bb-splice-extended-end-plate/form/step8'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_bb_splice_end_plate_step8_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
	$items['ddq-bb-splice-extended-end-plate/form/step9'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_bb_splice_end_plate_step9_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
	$items['ddq-bb-splice-extended-end-plate/form/step10'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_bb_splice_end_plate_step10_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
	$items['ddq-bb-splice-extended-end-plate/form/step11'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_bb_splice_end_plate_step11_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
	$items['ddq-bb-splice-extended-end-plate/form/step12'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_bb_splice_end_plate_step12_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
	$items['ddq-bb-splice-extended-end-plate/form/step13'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_bb_splice_end_plate_step13_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
		$items['ddq-bb-splice-extended-end-plate/form/step14'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_bb_splice_end_plate_step14_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
	$items['ddq-bb-splice-extended-end-plate/form/step15'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_bb_splice_end_plate_step15_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
	$items['ddq-bb-splice-extended-end-plate/form/step16'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_bb_splice_end_plate_step16_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
	$items['ddq-bb-splice-extended-end-plate/form/step17'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_bb_splice_end_plate_step17_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
	// Delete the comment
	$items['ddq-bb-splice-extended-end-plate/delete'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries) successful!'),
		'page callback' => 'ddq_bb_splice_end_plate_delete_comment',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
	// Success page.
	$items['ddq-bb-splice-extended-end-plate/success'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries) successful!'),
		'page callback' => 'ddq_bb_splice_end_plate_success',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
	// Result page
	$items['ddq-bb-splice-extended-end-plate/form/result'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'ddq_bb_splice_end_plate_result_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
	$items['ddq-bb-splice-extended-end-plate/form/result/download'] = array(
		'title' => t('BB Splice Extended End plate DDQ (Design and Detailing Queries)'),
		'page callback' => 'ddq_bb_splice_end_plate_result_generate_csv',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_end_plate.inc'
	);
	/***********************************************************/
	/****************** DDQ cleat angle  ******************/
	$items['ddq-cleat-angle/form'] = array(
		'title' => t('Cleat angle DDQ (Design and Detailing Queries)'),
		'page callback' => 'ddq_cleat_angle_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_cleat_angle.inc'
	);
	$items['ddq-cleat-angle/form/step1'] = array(
		'title' => t('Cleat angle DDQ (Design and Detailing Queries)'),
		'page callback' => 'ddq_cleat_angle_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_cleat_angle.inc'
	);
	$items['ddq-cleat-angle/form/step2'] = array(
		'title' => t('Cleat angle DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_cleat_angle_step2_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_cleat_angle.inc'
	);
	$items['ddq-cleat-angle/form/step3'] = array(
		'title' => t('Cleat angle DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_cleat_angle_step3_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_cleat_angle.inc'
	);
	$items['ddq-cleat-angle/form/step4'] = array(
		'title' => t('Cleat angle DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_cleat_angle_step4_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_cleat_angle.inc'
	);
	$items['ddq-cleat-angle/form/step5'] = array(
		'title' => t('Cleat angle DDQ (Design and Detailing Queries)'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_cleat_angle_step5_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_cleat_angle.inc'
	);
	// Delete the comment
	$items['ddq-cleat-angle/delete'] = array(
		'title' => t('Cleat angle DDQ (Design and Detailing Queries) successful!'),
		'page callback' => 'ddq_cleat_angle_delete_comment',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_cleat_angle.inc'
	);
	// Success page.
	$items['ddq-cleat-angle/success'] = array(
		'title' => t('Cleat angle DDQ (Design and Detailing Queries) successful!'),
		'page callback' => 'ddq_cleat_angle_success',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_cleat_angle.inc'
	);
	// Result page
	$items['ddq-cleat-angle/form/result'] = array(
		'title' => t('Cleat angle DDQ (Design and Detailing Queries)'),
		'page callback' => 'ddq_cleat_angle_result_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_cleat_angle.inc'
	);
	$items['ddq-cleat-angle/form/result/download'] = array(
		'title' => t('Cleat angle DDQ (Design and Detailing Queries)'),
		'page callback' => 'ddq_cleat_angle_result_generate_csv',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_cleat_angle.inc'
	);
	/*******************DDCL BB SPLICE COVER PLATE Bolted **************************/
	/******************************************************************************/
	$items['ddcl-bb-splice-cover-plate-bolted/form'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'ddcl_bb_splice_cover_plate_bolted_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step1'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'ddcl_bb_splice_cover_plate_bolted_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step2'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step2_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step3'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step3_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step4'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step4_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step5'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step5_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step6'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step6_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step7'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step7_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step8'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step8_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step9'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step9_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step10'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step10_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step11'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step11_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step12'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step12_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step13'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step13_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step14'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step14_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step15'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step15_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step16'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step16_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step17'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step17_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step18'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step18_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step19'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step19_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step20'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step20_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step21'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step21_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step22'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step22_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step23'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step23_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step24'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step24_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step25'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step25_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step26'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step26_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step27'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step27_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step28'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step28_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step29'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step29_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step30'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step30_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/step31'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddcl_bb_splice_cover_plate_bolted_step31_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	// Delete the comment
	$items['ddcl-bb-splice-cover-plate-bolted/delete'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'ddcl_bb_splice_cover_plate_bolted_delete_comment',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	// Success page.
	$items['ddcl-bb-splice-cover-plate-bolted/success'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'ddcl_bb_splice_cover_plate_bolted_success',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	// Result page
	$items['ddcl-bb-splice-cover-plate-bolted/form/result'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'ddcl_bb_splice_cover_plate_bolted_result_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddcl-bb-splice-cover-plate-bolted/form/result/download'] = array(
		'title' => t('DDCL BB Splice Cover Plate Bolted'),
		'page callback' => 'ddcl_bb_splice_cover_plate_bolted_result_generate_csv',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddcl_bb_splice_cover_plate_bolted.inc'
	);

	/*******************************************************************************/
	/*************************** DDQ BB Splice Cover Plate Bolted ******************/
	$items['ddq-bb-splice-cover-plate-bolted/form'] = array(
		'title' => t('DDQ BB Splice Cover Plate Bolted'),
		'page callback' => 'ddq_bb_splice_cover_plate_bolted_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddq-bb-splice-cover-plate-bolted/form/step1'] = array(
		'title' => t('DDQ BB Splice Cover Plate Bolted'),
		'page callback' => 'ddq_bb_splice_cover_plate_bolted_form_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddq-bb-splice-cover-plate-bolted/form/step2'] = array(
		'title' => t('DDQ BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_bb_splice_cover_plate_bolted_step2_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddq-bb-splice-cover-plate-bolted/form/step3'] = array(
		'title' => t('DDQ BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_bb_splice_cover_plate_bolted_step3_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddq-bb-splice-cover-plate-bolted/form/step4'] = array(
		'title' => t('DDQ BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_bb_splice_cover_plate_bolted_step4_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddq-bb-splice-cover-plate-bolted/form/step5'] = array(
		'title' => t('DDQ BB Splice Cover Plate Bolted'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			'ddq_bb_splice_cover_plate_bolted_step5_form'
		),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_cover_plate_bolted.inc'
	);
	// Delete the comment
	$items['ddq-bb-splice-cover-plate-bolted/delete'] = array(
		'title' => t('DDQ BB Splice Cover Plate Bolted successful!'),
		'page callback' => 'ddq_bb_splice_cover_plate_bolted_delete_comment',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_cover_plate_bolted.inc'
	);
	// Success page.
	$items['ddq-bb-splice-cover-plate-bolted/success'] = array(
		'title' => t('DDQ BB Splice Cover Plate Bolted successful!'),
		'page callback' => 'ddq_bb_splice_cover_plate_bolted_success',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_cover_plate_bolted.inc'
	);
	// Result page
	$items['ddq-bb-splice-cover-plate-bolted/form/result'] = array(
		'title' => t('DDQ BB Splice Cover Plate Bolted'),
		'page callback' => 'ddq_bb_splice_cover_plate_bolted_result_page',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_cover_plate_bolted.inc'
	);
	$items['ddq-bb-splice-cover-plate-bolted/form/result/download'] = array(
		'title' => t('DDQ BB Splice Cover Plate Bolted'),
		'page callback' => 'ddq_bb_splice_cover_plate_bolted_result_generate_csv',
		'page arguments' => array(),
		'access arguments' => array(
			'access osdag_feedback_form'
		),
		'file' => 'ddq_bb_splice_cover_plate_bolted.inc'
	);

	/******************************************************************************/
	return $items;
}
function osdag_response_form_permission()
{
	return array(
		"access osdag_feedback_form" => array(
			"title" => t("osdag feedback form"),
			"description" => t("Allows users to view osdag feedback form")
		),
		"access osdag_feedback_form_result" => array(
			"title" => t("osdag feedback form"),
			"description" => t("Allows users to view osdag feedback form result")
		)
	);
}
function _field_sentence_case($string)
{
	$string = ucwords(strtolower($string));
	foreach (array(
		'-',
		'\''
	) as $delimiter)
	{
		if (strpos($string, $delimiter) !== false)
		{
			$string = implode($delimiter, array_map('ucfirst', explode($delimiter, $string)));
		} //strpos($string, $delimiter) !== false
	} //array( '-', '\'' ) as $delimiter
	return $string;
}
